// <auto-generated />
using BoincStatistic.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoincStatistic.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20241029112753_boincStats")]
    partial class boincStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoincStatistic.Database.BoincStats.BoincStatsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<string>("CreditAvarage")
                        .HasColumnType("text");

                    b.Property<string>("CreditDay")
                        .HasColumnType("text");

                    b.Property<string>("CreditMonth")
                        .HasColumnType("text");

                    b.Property<string>("CreditUser")
                        .HasColumnType("text");

                    b.Property<string>("CreditWeek")
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .HasColumnType("text");

                    b.Property<string>("TotalCredit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BoincStats");
                });
#pragma warning restore 612, 618
        }
    }
}
